version: '2.4'

services:
  ps3netsrv:
    container_name: ps3netsrv
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./games:/games
    ports:
      - 38008:38008/tcp
    healthcheck:
      test: timeout 2 nc -z 127.0.0.1 38008
      interval: 1m
      timeout: 3s
